# Contains all custom serialization handler
services:
  UnitedCMS\CoreBundle\Field\FieldableFieldSettingsSerializationHandler:
    public: false
    tags:
      - { name: jms_serializer.handler, type: 'UnitedCMS\CoreBundle\Field\FieldableFieldSettings', format: 'json', method: 'handle' }

  UnitedCMS\CoreBundle\Collection\CollectionSettingsSerializationHandler:
    public: false
    tags:
      - { name: jms_serializer.handler, type: 'UnitedCMS\CoreBundle\Collection\CollectionSettings', format: 'json', method: 'handle' }