# Register all commands as services
services:

    UnitedCMS\CoreBundle\Command\CreateDomainCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator', '@united.cms.domain_definition_parser']
        tags:
            - { name: 'console.command', command: 'united:domain:create' }

    UnitedCMS\CoreBundle\Command\CreateOrganizationCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator']
        tags:
            - { name: 'console.command', command: 'united:organization:create' }

    UnitedCMS\CoreBundle\Command\CreatePlatformAdminCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator', '@security.password_encoder']
        tags:
            - { name: 'console.command', command: 'united:user:create' }