language: php
sudo: false
dist: trusty
os: linux

matrix:
    include:
        - php: 7.1.3
        - php: 7.1
          env: deps=high
        - php: 7.2
          env: deps=low

    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache/files

services:
    - mysql

env:
  - MYSQL_NAME=united_core_test
  - MYSQL_USER=travis

before_install:
  - composer self-update
  - composer require codeclimate/php-test-reporter --dev
  - mysql -e 'CREATE DATABASE united_core_test;'

install:
  - composer install

script:
  - phpunit

after_success:
  - vendor/bin/test-reporter